IMAGE_NAME = "generic/ubuntu1604"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 8192
        libvirt.cpus = 4
        libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
        libvirt.storage :file, :size => '50G'
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", bridge: "br0", dev: "br0", type: "bridge", mode: "bridge", ip: "192.168.1.175"
        master.vm.hostname = "ubu-work"
    end
end

