IMAGE_NAME = "generic/ubuntu1604"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :virtualbox do |virtualbox|
        virtualbox.memory = 4096
        virtualbox.cpus = 2
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", mode: "bridge", ip: "192.168.1.170"
        master.vm.hostname = "k8s-master"
# chef provisioning example
    #    config.vm.provision :chef_solo do |chef|
    #      chef.arguments = "--chef-license accept"
    #      chef.cookbooks_path = "cookbooks"
    #      chef.roles_path = "cookbooks/roles"
    #      chef.add_role("vagrant")
    #    end
    end
end

Vagrant.configure("2") do |config|
    config.ssh.insert_key = 'false'
    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 2
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "public_network", mode: "bridge", ip: "192.168.1.#{i + 170}"
            node.vm.hostname = "node-#{i}"
        end
    end
end
